### ISSUE TITLE
"Perform FFC" button in raspberrypi_video No longer works

### ISSUE THREAD

**Issue by belsinb** [groupgets/LeptonModule#17]
The previous iteration of the repo on my Pi worked fine, so I know I have the correct settings to communicate with my lepton via I2C.

However FFC doesn't work now ever since the github went from github.com/PureEngineering/LeptonModule to github.com/groupgets/LeptonModule. 

Also, I did run the executable with sudo.

**Comment by kekiefer** [comment]
It probably wasn't the move but rather subsequent changes made around then (e.g. pull request #14 or #16). Can you verify if this is the case? Maybe try running the code at version a9905796

**Comment by MartyMacGyver** [comment]
I'm not aware of any changes I made in #16 that would have caused FFC not to work (I've been using it without issues). Which subprogram are you using (e.g., raspberrypi_qt, raspberrypi_video, raspberrypi_capture)?

**Comment by MartyMacGyver** [comment]
Narrowing down, you must be using raspberrypi_video. I just re-downloaded the repo and rebuilt raspberrypi_video (qmake && make) and ran it - commanded FFC (by clicking "Perform FFC") works - I can hear and see the shutter closing and opening.

Did you download the current release to a clean area and rebuild it? Did you make any customizations previously (different I2C port, etc.)? Are you seeing video?

**Comment by PureEngineering** [comment]
did you enable the i2c module in the config.

**Comment by belsinb** [comment]
Yes, I am using raspberrypi_video.

Yes, I do have the I2C module enabled. 

No, I didn't make any customizations.

I'll try the build at a990579 to comfirm. 

Thanks you all for the tips.

**Comment by MartyMacGyver** [comment]
Let us know what exactly isn't working currently - just the FFC button? Something else as well (e.g., no video)?

**Comment by belsinb** [comment]
Turns out I was using such an old Lepton that the FFC function wasn't featured yet. Sorry for the confusion guys. haha

**Comment by MartyMacGyver** [comment]
No problem - thanks for the update!
