### ISSUE TITLE
Parameterize which i2c bus is used on the Pi

### ISSUE THREAD

**Issue by pcernek** [groupgets/LeptonModule#23]
Currently, the i2c bus to use on the Pi is hard-coded to `/dev/i2c-1` in the file `software/raspberrypi_libs/leptonSDKEmb32PUB/raspi_I2C.c`. For those who want to connect two Leptons to a single Raspberry Pi, taking advantage of the Pi's two i2c buses, it would be better if this were parameterized in this file and specified at a higher level.

**Comment by kekiefer** [comment]
For reference, the OP's [Google Groups post on this topic](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/flir-lepton/y6ljXkb0cnA).

Please let us know if you come up with a solution, we'll be happy to merge your pull request.

**Comment by kekiefer** [comment]
PR #24 merged

**Comment by wenyueqiang** [comment]
MY LEPTON IIC have no response!why
