### ISSUE TITLE
V4l2 Lepton

### ISSUE THREAD

**Issue by raspiuser200** [groupgets/LeptonModule#27]
Hello,

I'm using your Lepton module FLIR, and I'm trying to use the v4l2 program for converting module to a dev / videoX. But the result is not satisfactory

I'm using Raspberry (raspbian). I got the headers for the kernel version 4.4.8-v7 + I have, but when installing it gives error.
How did you hit one?

Nevertheless, I tried to compile and run your code, but I get an error v4l2 Sink.

Could you help me? Thank you and congratulations for your work.

**Comment by marty-sullivan** [comment]
Hi, were you able to install the v4l2loopback successfully and add it to the kernel with modprobe?

**Comment by raspiuser200** [comment]
Hi @marty-sullivan 

Yes, I tried to install v4l2loopback, with several different kernels 4.4. and  4.1.XX-v7 , , but I can't successfully run modprobe v4l2loopback.

If you did a raspberry, you could comment me like?

Because I am referring to the github of v4l2loopback, and I couldn't get it.

Sorry for the inconvenience. And thanks in advance.
 .

**Comment by marty-sullivan** [comment]
Here are the steps I took to compile the v4l2loopback kernel module on a raspberry pi:

1. Install kernel headers with [rpi-source](https://github.com/notro/rpi-source) utility.
2. Compile [v4l2loopback source](https://github.com/umlaeute/v4l2loopback)
3. If step 2 is successful, you should have v4l2loopback.ko in the source directory
4. Copy v4l2loopback.ko to /lib/modules (I believe just /lib/modules directory works, but if that doesn't work, put it in /lib/modules/$(uname -r) ).
5. You might find insmod works too, I just copied the file like step 4 says
6. At this point, you should be able to `modprobe v4l2loopback`

Beware that updating kernel means you will have to recompile v4l2loopback by following these steps again.

**Comment by raspiuser200** [comment]
Hi @marty-sullivan 

THANKS!

Apparently it was a problem with my kernel and headers used to. I had downloaded from another website but by using the tool you have told me has been fixed (RPI-source).
Thanks for the reply speed. I was very disappointed because I couldn't find the error, and finally works.

**Comment by Cullpepper** [comment]
Hi Marty,

I think I installed everything correctly, but trying to launch v4l2lepton gives me this code:
"Waiting for sink"
"done reading, rests"

And that's it. Any suggestions?

**Comment by Cherry97Pepis** [comment]
Hi Cullpepper,
I have the same problem. I'm trying to stream thermal video from Lepton 2.5 through Raspberry Pi 4B to my iOS app. It's kind of prototype of drone with thermal vision. 
When I start the ./v4l2lepton I get "Waiting for sink", sometimes I get sth weird on the screen in VLC, but usually I get nothing :( 
Have you any idea to fix it? 
I try most of ways to fix it, but people say "wow, it working" and I can only say "nope, still nothing change" :P

**Comment by Cullpepper** [comment]
Oh heck, that was 5 years ago, I barely remember now. 

Your issue could be totally different but If I recalL, my problem turned out to be the physical housing of the flir in the board- the sensor is only loosely fitted to the contact points and I had to pop it out and re-seat it.

**Comment by Cherry97Pepis** [comment]
Oh Thx for reply 
I’m really broken abt my project 
That is my master Thesis and i have two weeks to finish it 

I will try to check the camera as u say. Maybe that will help 
Thanks a lot :) 

> Wiadomość napisana przez Cullpepper ***@***.***> w dniu 16.07.2021, o godz. 17:07:
> 
> ﻿
> Oh heck, that was 5 years ago, I barely remember now. 
> 
> Your issue could be totally different but If I recalL, my problem turned out to be the physical housing of the flir in the board- the sensor is only loosely fitted to the contact points and I had to pop it out and re-seat it. 
> 
> 
> 
> Sent from my iPhone
>

**Comment by EdwinNavarro** [comment]
Hi Cherry,
Were you able to fix your issue? 
I wonder if this still works

**Comment by Cherry97Pepis** [comment]
Hi Edwin, 
Yes, I fixed my issue, I had to use v4l2loopback kernel module and Motion program. V4l2loopback helped me to create virtual video device and stream image from camera. My RaspberryPi didn't recognise FLIR camera before so I had no other choice and fast way to stream video. When I created virtual device in v4l2loopback i was able to see the image from my camera in VLC player.
Motion program was used to send video to my iOS App :)
If you have any questions just ask :) It was some time ago, but maybe my master thesis will help :)

**Comment by EdwinNavarro** [comment]
I want to do something similar to what you did. However I was planning on writing a gui, and thermal feed would be done by using opencv, then stream it using vnc viewer. I haven’t been able to open the thermal stream using opencv. I need to control some gpio pins as digital outputs. An iOS app would be better though
