### ISSUE TITLE
No auto colour adjust

### ISSUE THREAD

**Issue by BdT141** [groupgets/LeptonModule#45]
Hi, thank you so much for your code! Is it possible to not have the raspberry pi video app auto adjust the colours to the hottest object in the frame. I'm hoping that if the temp/colour scale is constant I can determine temperature from the image?

Thanks,
Brandon

**Comment by tmsd2001** [comment]
Hello, you can set the range to a fix value, but the output is depends on the camera module temperature.
I am thinking of building a reference source, which I then put in the picture.
A small box with Arduino and a Heater.
regards
ThomasD
