### ISSUE TITLE
Very low quality and intermittent images

### ISSUE THREAD

**Issue by xzheng77** [groupgets/LeptonModule#64]
After downloading and compiling all the code for Lepton 3.5 thermal camera, I ran raspberrypi_video, it was able to output the video, but the resolution of video was very bad, and intermittent. Any idea what cause the problem? And how to fix it. 
PS: I am new to raspberry pi.

**Comment by pasmitchell21** [comment]
> After downloading and compiling all the code for Lepton 3.5 thermal camera, I ran raspberrypi_video, it was able to output the video, but the resolution of video was very bad, and intermittent. Any idea what cause the problem? And how to fix it.
> PS: I am new to raspberry pi.

Did you figure this out?

**Comment by veskoch** [comment]
Same issue. The image appears "interlaced" (see attached).
![image](https://user-images.githubusercontent.com/6517175/64617076-b0d8be00-d3d5-11e9-95f7-eae58d0b004e.png)

This is on a Raspberry Pi 4, with Flit Lepton 3.5, using the standard breakout board by GetLab.

I see that in `main.cpp` the resolution is set to 320x240, and the Lepton is outputting 160x120 (link below). Can the issue be linked to that?

https://github.com/groupgets/LeptonModule/blob/1bc9aa08622e9b686c2ec90b95fa3dedd09d9166/software/raspberrypi_video/main.cpp#L26

**Comment by kekiefer** [comment]
This code is not compatible with the Lepton 3. That is why the image looks like this, it's actually 80x60 frames.
