### ISSUE TITLE
v412lepton is not working with Lepton3.5

### ISSUE THREAD

**Issue by spk921** [groupgets/LeptonModule#65]
I am using Lepton3.5 and when I compile and run the v412lepton it just not showing any error messages and not working. I have changed the resolution parameters and set device location as  /dev/video0. What should I change to use the code for Lepton 3.5 version one.

**Comment by marty-sullivan** [comment]
v4l2lepton has not been updated to work with the Lepton 3 series, it will only work with Lepton 2 or 2.5. The code can probably be updated to work with 3/3.5 but I don't have the time to commit to updating nor do I have a Lepton 3 to test with.
